version: "3"

services:
  app:
    build: .
    command: npm start
    ports:
      - "3006:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - "mysql"
    networks:
      - backend

  mysql:
    container_name: "mysql-node"
    platform: linux/amd64
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    networks:
      - backend

networks:
  backend:
    driver: bridge